server:
  port: 9001
spring:
  dubbo:
    application:
      name: dubbo-provider
    registry:
      address: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183
    protocol:
      name: dubbo
      port: 20880
    scan: org.com.ck